# -*- coding: utf-8 -*-
"""raw data process.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BYlBFWLRIsdBEPwSkmt3JBKNQUwVF400
"""

import pandas as pd

df = pd.read_csv('C:/Users/athen/Documents/cw/bnrawdata.csv', index_col =False)

df.loc[df.case<=20,'case']=1
df.loc[(df.case>20) & (df.case<=40),'case']=2
df.loc[(df.case>40) & (df.case<=60),'case']=3
df.loc[(df.case>60) & (df.case<=80),'case']=4
df.loc[(df.case>80) & (df.case<=100),'case']=5
df.loc[(df.case>100) & (df.case<=120),'case']=6
df.loc[(df.case>120) & (df.case<=140),'case']=7
df.loc[(df.case>140) & (df.case<=160),'case']=8
df.loc[(df.case>160) & (df.case<=180),'case']=9
df.loc[df.case>180,'case']=10

df.loc[df.death<=3,'death']=1
df.loc[(df.death>3) & (df.death<=6),'death']=2
df.loc[(df.death>6) & (df.death<=9),'death']=3
df.loc[(df.death>9) & (df.death<=12),'death']=4
df.loc[(df.death>12) & (df.death<=15),'death']=5
df.loc[(df.death>15) & (df.death<=18),'death']=6
df.loc[(df.death>18) & (df.death<=21),'death']=7
df.loc[(df.death>21) & (df.death<=24),'death']=8
df.loc[(df.death>24) & (df.death<=27),'death']=9
df.loc[df.death>30,'death']=10

df.loc[df.test>1,'test']=5
df.loc[(df.test>0.75) & (df.test<=1),'test']=4
df.loc[(df.test>0.5) & (df.test<=0.75),'test']=3
df.loc[(df.test>0.25) & (df.test<=0.5),'test']=2
df.loc[df.test<=0.25,'test']=1

df.loc[df.beds<=4, 'beds']=1
df.loc[(df.beds>4) & (df.beds<=8),'beds']=2
df.loc[(df.beds>8) & (df.beds<=12),'beds']=3
df.loc[df.beds>12,'beds']=4

print(df)
df.to_csv('C:/Users/athen/Documents/cw/bndata.csv', index=False)